### ISSUE TITLE
Create issue and PR templates

### ISSUE THREAD

**Issue by siddhant-khisty** [virtual-tech-school/learn-by-doing-app#3]
Create sample templates for Issues and PRs. Let us include the following information
[ ] What is the scope of the issue/PR?
[ ] What files does this PR change / issue propose to change
[ ] Does it follow the best practices mentioned in the contribution guide?

**Comment by prakharporwal** [comment]
created #7 for this issue.

**Comment by prakharporwal** [comment]
What kind of issue template should we make ?
I have added for
 
[] doc report
[] bug report
[] other

**Comment by siddhant-khisty** [comment]
@prakharporwal We can also add the following

- Feature request/addition
- Suggested improvements to existing feature
